### ISSUE TITLE
How to Use the Multi Image Customizer

### ISSUE THREAD

**Issue by keeneyemedia** [lucatume/tad-libs-for-wordpress#1]
Hi... I read through your posts about the multi image customizer, and its exactly what I need. I've installed your entire library into my mu-plugins folder, but when I try to add a multi image field, I get an error. Could you just drop me a quick note on how to actually use it?

My current code looks like this, but is telling me the 'MultiImageCustomControl' class can't be found...

```php
$wp_customize->add_setting( 'gallery-images' );
	 
	$wp_customize->add_control(
	    new MultiImageCustomControl(
	        $wp_customize,
	        'images',
	        array(
	            'label' => 'Gallery Images',
	            'section' => 'gallery',
	            'settings' => 'gallery-images'
	        )
	    )
	);
```

**Comment by lucatume** [comment]
Hi,

This repository is kind of deprecated but I will look into it in the next days, thanks for your interest,

Luca

**Comment by lucatume** [comment]
Hi, I've extracted the code of the Multi Image Control to a [a new repo](https://github.com/lucatume/multi-image-control), have a look.
